### ISSUE TITLE
compilation error with all targets

### ISSUE THREAD

**Issue by signorello** [Grace-TL/MV-Sketch#1]
Compiling any target (main_hitter, main_changer, main_simd)  will raise a very similar error. For example, when compiling the main_hitter.cpp, you get:

 _main_hitter.cpp:93:62: error: call of overloaded ‘abs(long unsigned int)’ is ambiguous
                          error += abs(res->second - it->second)*1.0/it->second;_

From a very quick look at your code, it looks like the above problem is that you call _abs_ with the result of an 'uint64_t' (res-> second is a val_tp type which is defined in datatypes.hpp) which raises the above error because that call does not match any of the _abs_ function signatures and, btw, I would guess that call to abs would be useless too (if an unsigned gets negative, will it not be automatically wrapped up?).

Anyway, if you change val_tp in datatypes.hpp from 'uint64_t' to int, the error goes away and your code compiles all make targets  fine. 

I hope the above information helps, best

**Comment by Grace-TL** [comment]
The information is quite helpful! Thanks for reporting.
